/*
    When typescript compiles a file it needs to have references to all files definitions from which are used in the file.
    You can place all required links at the top of each file but it is to hard to maintain.
    Hence every ts file in the project references only this file that in its turn references all ts files.
    This file is auto-generated by 'sails-linker' grunt task.
 */

/// <reference path="../../typings/tsd" />

///<!-- inject:ts -->
/// <reference path="app.ts" />
/// <reference path="common/appSettings.ts" />
/// <reference path="common/module.ts" />
/// <reference path="common/pagedData.ts" />
/// <reference path="common/routingConfig.ts" />
/// <reference path="emails/common/filterService.ts" />
/// <reference path="emails/email.ts" />
/// <reference path="emails/emailsApi.ts" />
/// <reference path="emails/emailsLoader.ts" />
/// <reference path="emails/emailsParser.ts" />
/// <reference path="emails/list/listController.ts" />
/// <reference path="emails/list/listSideBarController.ts" />
/// <reference path="emails/module.ts" />
/// <reference path="emails/view/fullViewDirective.ts" />
/// <reference path="emails/view/shortViewDirective.ts" />
/// <reference path="emails/view/viewController.ts" />
/// <reference path="emails/view/viewSideBarController.ts" />
///<!-- endinject -->
